### PR TITLE
Don't set cycle duration in stone

### PR DESCRIPTION
**Pull request by jeromegn**
Once the cycle duration was set, it couldn't be changed later. Maybe this isn't the best fix, but it does work.

### CODE REVIEW

**Comment by vrish88** [comment]
Thanks. This is a definite improvement. I'll take some time to refactor this and #1 soon.

**Comment by jeromegn** [comment]
Crap, I tested it and it wasn't so perfect. I changed it in the master branch of http://github.com/jeromegn/sinatra_cyclist

**Comment by shushiej** [comment]
Im running dashing for sinatra cyclist, and i followed the instructions for the dashing part, i am assuming that 
set :routes_to_cycle_through, [:dashboard_1, :dashboard_2] where dashboard_1 and dashboard_2 are the .erb files that are under the dashboard directory? but i dont have a _cycle route, i dont know why, do i have to create it ?

**Comment by vrish88** [comment]
You shouldn't have to create a _cycle route, that's provided in the gem. What error are you encountering?

My guess is that your require statements may be out of order. Did you require sinatra cyclist before dashing?

``` ruby
require "sinatra/cyclist"
require 'dashing'
```

If not you'll see an error like "No such file or directory - sample/dashboards/_cycle.erb"

**Comment by shushiej** [comment]
Thanks for the reply,
The error is that the dashboards are not rotating at all. it just stays the
same. I have two dashboards which i have mentioned in the config.ru:  set
:routes_to_cycle_through, [:dashboard1, :dashboard_2]
I have put the require statements in the correct order (just checked now).

**Comment by vrish88** [comment]
The only other thing I can think of is make sure your files and routes are named the same. In your comment you have: [:dashboard1, :dashboard_2] with the first dashboard missing a _ before the number. I dunno if that was a type or actually from your code base.

Otherwise, I'm sorry, I just don't know what else it could be. With more context I may be able to help more.

**Comment by shushiej** [comment]
Yeah that was a typo sorry, in my file they are named correctly.
This is how my config.ru looks like, and the names are the same as the
dashboards, however im not sure where the duration of each board is placed?
So are u saying that the gem will do the actual cycling, because the
config.ru is pretty much the only file i modified to try and make it work,
are there any other files that i need to modify (apart from the gem file) .
Thanks a lot for ur help/.

require 'sinatra/cyclist'
require 'dashing'
require 'timezone'

configure do
  set :auth_token, 'XERO_SX'
  #set :default_dashboard, 'billing_xero'

  helpers do
    def protected!
     # Put any authentication code you want in here.
     # This method is run before accessing any resource.
    end
  end
end

map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

set :routes_to_cycle_through, [:billing_xero, :cs_xero]

run Sinatra::Application

**Comment by vrish88** [comment]
Hrm yeah that all looks ok. So if you go to /_cycle what page does it show? Then does it "refresh" that page or does that page just stay fixed on the screen? Because what should happen is that you go to that page it stays there for a bit and then the http refresh header should kick in, sending the browser back to /_cycle.

To be honest I haven't used this gem in a couple months so maybe you are running a newer version of Sinatra or dashing and that's what is causing this issue.

**Comment by shushiej** [comment]
i tried, localhost:3030/cycle and it said "Drats the dashboard does not
exist" and then i tried localhost:3030/billing_xero/cycle and it said the
same thing,

Yeah maybe it could be an update issue, Have no idea whats wrong with it
lol.

Thanks a lot for your help though, much appreciated.

**Pull request merged**
