### PR TITLE
Added the ability to set the cycle duration from your config.ru configuration block

### PR DESCRIPTION
**Pull request by kevintuhumury**
The default is still 3 seconds. Whenever the `duration` parameter is set, it will be saved to the session and it will be used as the cycle duration.

If you would like the default to be 30 seconds, you can override this behavior by specifying the following in your Dashing config.ru:

``` ruby
configure do
  set :auth_token, 'YOUR_AUTH_TOKEN'
  set :routes_to_cycle_through, [:dashboard_1, :dashboard_2, :dashboard_3]
  set :cycle_duration, 30
  ...
```

You'll still be able to set the duration with the GET parameter. Once that's set, it will keep that value during the session.

### CODE REVIEW

**Comment by vrish88** [comment]
I'll publish another version of the gem as well.

**Comment by vrish88** [comment]
Thanks!

**Comment by tdonelson** [comment]
Great, thanks for this.

**Comment by vrish88** [comment]
Gem released!

**Pull request merged**
